/**
 * forensicReportEngine.ts — Court-Style Forensic Report Generator
 * Aivora Audio Infrastructure Platform
 */

import type { ProvenanceScore }  from "./provenanceEngine";
import type { ForensicReport }   from "../audioForensics/forensicPipeline";

export interface CourtReport {
  caseId:         string;
  generatedAt:    string;
  fileHash:       string;
  analyst:        string;
  markdown:       string;
  jsonManifest:   string;
  reproducible:   boolean;
  verificationTrace: string[];
}

export class ForensicReportEngine {
  generate(
    provenance: ProvenanceScore,
    forensic:   Partial<ForensicReport>,
    fileId:     string,
    analyst     = "Aivora Forensic Agent"
  ): CourtReport {
    const caseId=`CASE-${Date.now().toString(36).toUpperCase()}`;
    const now=new Date().toISOString();

    const trace=[
      `[${now}] Analysis initiated`,
      `[${now}] Provenance score: ${provenance.overall}/100`,
      `[${now}] Verdict: ${provenance.verdict.toUpperCase()}`,
      `[${now}] Evidence items: ${provenance.evidence.length}`,
      `[${now}] Report generated: ${caseId}`,
    ];

    const lines=[
      `# AIVORA FORENSIC REPORT`,
      `**Case ID:** ${caseId}  **Date:** ${now}  **Analyst:** ${analyst}`,
      "",
      "## EXECUTIVE SUMMARY",
      `**Verdict:** ${provenance.verdict.toUpperCase().replace("_"," ")}`,
      `**Provenance Score:** ${provenance.overall}/100`,
      `**Confidence:** ${provenance.overall>80?"HIGH":provenance.overall>60?"MEDIUM":"LOW"}`,
      "",
      "## FORENSIC METRICS",
      `| Dimension | Score | Status |`,
      `|-----------|-------|--------|`,
      `| Synthetic Risk | ${(provenance.syntheticRisk*100).toFixed(1)}% | ${provenance.syntheticRisk>0.5?"⚠ SUSPICIOUS":"✓ NATURAL"} |`,
      `| Voice Consistency | ${(provenance.voiceConsistency*100).toFixed(1)}% | ${provenance.voiceConsistency>0.8?"✓ CONSISTENT":"⚠ INCONSISTENT"} |`,
      `| Room Consistency | ${(provenance.roomConsistency*100).toFixed(1)}% | ${provenance.roomConsistency>0.8?"✓ CONSISTENT":"⚠ INCONSISTENT"} |`,
      `| Mic Consistency | ${(provenance.micConsistency*100).toFixed(1)}% | ${provenance.micConsistency>0.8?"✓ CONSISTENT":"⚠ INCONSISTENT"} |`,
      `| AI Artifact Risk | ${(provenance.aiArtifactRisk*100).toFixed(1)}% | ${provenance.aiArtifactRisk>0.3?"⚠ DETECTED":"✓ CLEAN"} |`,
      `| Timeline Tamper | ${(provenance.tamperRisk*100).toFixed(1)}% | ${provenance.tamperRisk>0.3?"⚠ SUSPICIOUS":"✓ CLEAN"} |`,
      "",
      "## EVIDENCE",
      ...(provenance.evidence.length>0
        ? provenance.evidence.map(e=>`- ${e}`)
        : ["- No significant anomalies detected"]),
      "",
      "## INTEGRITY",
      `| Field | Value |`,
      `|-------|-------|`,
      `| File ID | ${fileId} |`,
      `| Case ID | ${caseId} |`,
      `| Duration | ${forensic.durationSec??0}s at ${forensic.sampleRate??48000}Hz |`,
      "",
      "---",
      `*Generated by Aivora Forensic Engine v2.0 | Reproducible: YES*`,
    ];

    const manifest={
      caseId, fileId, analyst, timestamp:now,
      provenance, verdict:provenance.verdict,
      reproducible:true, verificationTrace:trace,
    };

    return {
      caseId, generatedAt:now, fileHash:fileId, analyst,
      markdown:lines.join("\n"),
      jsonManifest:JSON.stringify(manifest,null,2),
      reproducible:true,
      verificationTrace:trace,
    };
  }

  download(report:CourtReport): void {
    const blob=new Blob([report.markdown],{type:"text/markdown"});
    const a=document.createElement("a");
    a.href=URL.createObjectURL(blob);
    a.download=`forensic_${report.caseId}.md`;
    a.click();
  }
}

export const forensicReportEngine = new ForensicReportEngine();
